import Head from 'next/head'
import { getProducts } from '@/api-routes/getProducts'
import Products from '@/components/products/products'
import { useEffect, useState } from 'react'
import { Product } from '@/types/products'
import Button from '@/components/button/Button'
import styles from '@/styles/index.module.css'

export default function Home() {
  const [products, setProducts] = useState<Array<Product> | undefined>(undefined)
  const [disabled, setDisabled] = useState(false)

  useEffect(() => {
     const fetchData = async () => {
        const data: Array<Product> = await getProducts(0);
        setProducts(data);
    }
    fetchData();
  }, []);

  const viewMoreProducts = async (): Promise<void> => {
    if (products !== undefined) {
      const data: Array<Product> = await getProducts(products?.length);
      setProducts(data);
    }
  }

  useEffect(() => {
    products?.length === 20 ? setDisabled(true) : ''
  }, [products])

  return (
    <>
      <Head>
        <title>A Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section className={styles.productSection}>
          <Products products={products} />
          {!disabled && <Button value='SEE MORE' onClick={viewMoreProducts} className='button' />}
        </section>
      </main>
    </>
  )
}
